### ISSUE TITLE
Mini-Shell 4주차

### ISSUE THREAD

**Issue by highjcho** [highjcho/MINI-SHELL#37]
jonkim

- [x] init&free 만들기
- [x] signal 처리

hyunjcho

- [x] builtin  execute 프로세스 수정
- [x] env ? 추가 및 ? 관련 로직 생성
- [x] here_doc 처리

공통

- [x] 형식 통일
- [x] 전체 예외 처리 (프로세스 중 할당 오류 등으로 프로그램 비정상 종료 시  exit 처리)

**Comment by dino9881** [comment]
1. 시그널
2. 종료코드 업데이트
3. 예외처리(각종 fail 시... syntax 오류 등...)
4. 놈
5. 누수체크
6. 테스트

**Comment by dino9881** [comment]
빈문자열 체크

**Comment by dino9881** [comment]
- [ ] init 모아서 처리
- [ ] paser 종료코드 처리
- [ ] free 처리 
- [ ] 예외 , 누수 처리
- [ ] norm

**Comment by dino9881** [comment]
<> || syntax error -> 258
< a (if !a) -> 1

**Comment by dino9881** [comment]
- [x] env 통일 
- [x] norm
- [x] makefile 정리
- [x] 발표 정리
- [x] readline history 생각하기
